---
- name: Развертывание приложения
  hosts: app
  become: true
  gather_facts: true

  roles:
    - role: ../roles/docker
    - role: ../roles/deploy_compose
      vars:
        deploy_compose_deploy_target_dir: /opt/app
        deploy_compose_deploy_compose_file: docker-compose.app.yml
        deploy_compose_deploy_project_name: app
