---
- name: Настройка сервера мониторинга
  hosts: monitoring
  become: true
  gather_facts: true

  roles:
    - docker
    - role: deploy_compose
      vars:
        deploy_compose_deploy_target_dir: /opt/monitoring
        deploy_compose_deploy_compose_file: docker-compose.monitoring.yml
        deploy_compose_deploy_project_name: monitoring
