---
deploy_compose_deploy_src: "{{ playbook_dir }}/../deploy"
deploy_compose_deploy_target_dir: /opt/app
deploy_compose_deploy_compose_file: docker-compose.app.yml
deploy_compose_deploy_project_name: stack
