apiVersion: 1

policies:
  - orgId: 1
    receiver: "Telegram"
    group_by:
      - "grafana_folder"
      - "alertname"
    # Ждём 30 секунд перед первой отправкой — сглаживаем кратковременные сбои
    group_wait: 30s
    # Интервал между группами уведомлений
    group_interval: 5m
    # Повторять если алерт не погас
    repeat_interval: 4h
