---
- name: Развертывание приложения
  hosts: app
  become: true
  gather_facts: true

  roles:
    - role: docker
    - role: deploy_compose
      vars:
        deploy_target_dir: /opt/app
        deploy_compose_file: docker-compose.app.yml
        deploy_project_name: app
